apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s
spec:
  replicas: 3                     # Solo 3 pod por ahora
  selector:
    matchLabels:
      app: app-k8s
  template:
    metadata:
      labels:
        app: app-k8s
    spec:
      containers:
        - name: app-k8s
          image: app-k8s-local:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
  
          # Health checks
          livenessProbe: ## Verifica si el contenedor está vivo
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe: ## Verifica si el contenedor está listo para recibir tráfico
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_VERSION