apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s
spec:
  replicas: 3                     # Solo 1 pod por ahora
  selector:
    matchLabels:
      app: app-k8s
  template:
    metadata:
      labels:
        app: app-k8s
    spec:
      containers:
        - name: app-k8s
          image: app-k8s-local:2.0
          imagePullPolicy: Never     # local image
          ports:
            - containerPort: 8080