apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  type: NodePort
  selector:
    app: app-k8s
  ports:
    - port: 80                      # service port
      targetPort: 8080              # container port
      nodePort: 30080               # localhost port